### ISSUE TITLE
Protocol not prompting user to get the input (i.e. LB powder) in the beginning 

### ISSUE THREAD

**Issue by joonseokii** [aquarium-bio/issues#13]
o.input.all.take is not functioning as need be.

**Comment by klavins** [comment]
I have implemented take for the situation where only a container type is specified.

**Comment by joonseokii** [comment]
I'm still seeing this error:    
   - Unimplemented: take item container ispec.





Joonseok Lee 


     On Friday, October 9, 2015 10:56 AM, Eric Klavins <notifications@github.com> wrote:
   

 I have implemented take for the situation where only a container type is specified. —
